name: Test Action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - run: echo "Hello World"
      - run: cat /etc/os-release
      - run: lsb_release -a
      - run: arch
      - run: uname -a
      # - run: sudo apt install neofetch -y
      # - run: neofetch
      - run: pwd
      - run: ls
      - run: ls /
      - run: mount

