name: Test Action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - run: echo "Hello World"
      - run: cat /etc/os-release
      - run: lsb_release -a > lsb_release
      - run: arch > arch
      - run: uname -a > uname-a

      - name: Checkout
        uses: actions/checkout@v2.7.0

      - run: pwd
      - run: ls

      - run: cat README.md

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: test-release
          tag: temporary-tag
          draft: true
          omitBody: true
          artifacts: |
            /etc/os-release
            lsb_release
            arch
            uname-a




    
