name: Test Action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0

      - run: cat README.md

      - run: echo "Hello World"
      - run: cat /etc/os-release
      - run: lsb_release -a > lsb_release
      - run: arch > arch
      - run: uname -a > uname-a

      - run: pwd
      - run: ls

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: my-artifact
      #     path: |
      #       /etc/os-release
      #       lsb_release
      #       arch
      #       uname-a


      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: test-release
          body: |
            This is the temporary release.
          tag: temporary-tag
          draft: true
          omitBody: true
          artifacts: |
            /etc/os-release
            lsb_release
            arch
            uname-a
          token: ${{ secrets.GITHUB_TOKEN }}




    
