name: Test Action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
        
    steps:
      - name: "Hello World"
        run: | 
          echo "Hello World"
          cat /etc/os-release
          lsb_release -a
          arch
          uname -a
          
