name: Test Action

on:
  push:
    tags:
      - "*"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
        
    steps:
      - name: "Hello World"
        run: echo "Hello World"
